/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import cn.pengh.demo.hello.mvc.Run;
import cn.pengh.demo.hello.mvc.util.LogUtil;
import org.junit.Test;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        LogUtil.getLogger().debug("Test..");
        Run.main(null);
    }
}
