package cn.pengh.dubbo.provider.city.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import cn.pengh.mvc.orm.type.TrimStringUserType;
/**
 * 
 * @author pengh
 * @Date 2016年6月29日 下午2:51:10
 */

@Entity
@Table(name="t_phone_city")//mysql,ccsdb
@DynamicInsert
@DynamicUpdate
@TypeDefs({@TypeDef(name = "trimStringUserType",typeClass = TrimStringUserType.class,defaultForType = String.class)})
public class PhoneCityModel {
	/* auto generated by penghcn 2016-06-29 14:49:42 */
	@Id
	@Type(type="trimStringUserType")
	@Column(name="phone_bin",length=7)
	private String phoneBin;

	@Column(name="city_id")
	private Integer cityId;

	@Column(name="brand_id")
	private Byte brandId;

	public String getPhoneBin() {
		return phoneBin;
	}

	public void setPhoneBin(String phoneBin) {
		this.phoneBin = phoneBin;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Byte getBrandId() {
		return brandId;
	}

	public void setBrandId(Byte brandId) {
		this.brandId = brandId;
	}
}
