package cn.pengh.dubbo.provider.city.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import cn.pengh.mvc.orm.type.TrimStringUserType;
/**
 * 
 * @author pengh
 * @Date 2016年6月29日 下午2:51:30
 */

@Entity
@Table(name="t_city")//mysql,ccsdb
@DynamicInsert
@DynamicUpdate
@TypeDefs({@TypeDef(name = "trimStringUserType",typeClass = TrimStringUserType.class,defaultForType = String.class)})
public class CityModel implements Serializable{
	private static final long serialVersionUID = 7758961175653983742L;

	/* auto generated by penghcn 2016-06-29 14:47:53 */
	@Id
	@Column(name="city_id")
	private Integer cityId;

	@Type(type="trimStringUserType")
	@Column(name="city_nm",length=120)
	private String cityNm;

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getCityNm() {
		return cityNm;
	}

	public void setCityNm(String cityNm) {
		this.cityNm = cityNm;
	}
}
